#!/usr/bin/env python3
"""Generate src/collapse_table.rs from the reference's own Unicode data.

The reference pre-tokenizer does not ask a Unicode library for categories: it
reads `unicode_ranges_flags` and `unicode_set_whitespace` from its
src/unicode-data.cpp, and for every codepoint >= 0x80 it substitutes one
"collapsed" byte (src/unicode.cpp, `unicode_regex_split`):

    whitespace            -> 0x0B
    NUMBER                -> 0xD1
    LETTER                -> 0xD2
    PUNCTUATION           -> 0xD3
    ACCENT_MARK           -> 0xD4
    SYMBOL                -> 0xD5
    anything else         -> 0xD0

A different Unicode version would split some text differently, so the table
is derived from that file and nothing else. Usage:

    python3 gen-collapse-table.py <ik>/src/unicode-data.cpp > ../src/collapse_table.rs
"""
import hashlib
import re
import sys

MAX = 0x110000
CAT = {0x0002: 0xD1, 0x0004: 0xD2, 0x0020: 0xD3, 0x0010: 0xD4, 0x0040: 0xD5}


def block(src, name):
    start = src.index(name)
    body = src[src.index("{", start) + 1:]
    return body[:body.index("\n};")]


def main():
    path = sys.argv[1]
    raw = open(path, "rb").read()
    src = raw.decode("utf-8")
    ranges = [(int(a, 16), int(f, 16))
              for a, f in re.findall(r"\{0x([0-9A-Fa-f]+), 0x([0-9A-Fa-f]+)\}",
                                     block(src, "unicode_ranges_flags ="))]
    assert ranges[0][0] == 0 and ranges[-1][0] == MAX, "range table must span 0..MAX"
    white = {int(x, 16) for x in re.findall(r"0x([0-9A-Fa-f]+)", block(src, "unicode_set_whitespace ="))}

    cls = bytearray(MAX)
    for (lo, flags), (hi, _) in zip(ranges, ranges[1:]):
        c = CAT.get(flags & 0x00FF, 0xD0)
        cls[lo:hi] = bytes([c]) * (hi - lo)
    for w in white:
        cls[w] = 0x0B

    out = []
    prev = None
    for cpt in range(0x80, MAX):
        if cls[cpt] != prev:
            out.append((cpt, cls[cpt]))
            prev = cls[cpt]

    md5 = hashlib.md5(raw).hexdigest()
    print("// @generated by tools/gen-collapse-table.py from the reference's")
    print(f"// src/unicode-data.cpp (md5 {md5}). Do not edit by hand.")
    print("// The table is derived from that file, Copyright (c) the ggml, llama.cpp and ik_llama.cpp authors,")
    print("// MIT License; the full notice is in THIRD_PARTY_NOTICES.md at the repository root.")
    print("")
    print("/// `(first codepoint, collapsed byte)` for every run of codepoints >= 0x80")
    print("/// that share a collapsed byte; a run ends where the next one starts, the")
    print("/// last one at 0x110000.")
    print(f"pub(crate) static RUNS: [(u32, u8); {len(out)}] = [")
    for cpt, c in out:
        print(f"    (0x{cpt:06X}, 0x{c:02X}),")
    print("];")


main()
