[package]
name = "bloomery-model"
version = "0.1.0"
edition = "2024"
publish = false
license = "MIT"

[lib]
name = "model"

[lints]
workspace = true

[dependencies]
bloomery-gguf = { path = "../gguf" }
bloomery-qdot = { path = "../qdot" }
bloomery-threads = { path = "../threads" }
libc = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
